# Generated by Django 4.1.2 on 2022-10-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
                ('field_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassesQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.TextField(blank=True, null=True)),
                ('property_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes_query',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('field', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fields',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('object', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjectsQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('property_id', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objects_query',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('info', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'properties',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QueryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('relation_id', models.TextField(blank=True, null=True)),
                ('class_id', models.TextField(blank=True, null=True)),
                ('property_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'query_table',
                'managed': True,
            },
        ),
    ]
