# Generated by Django 3.2.9 on 2022-11-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosystem', '0003_auto_20221105_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fields',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objectsquery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
